<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>L2</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>12</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>918.6500519837339</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>233.0</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>280.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>446.6069140441723</CalcMass>
                    <CalcCG>280.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>508.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>101.6</BaseDia>
                    <ShoulderLen>101.6</ShoulderLen>
                    <ShoulderOD>98.425</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>82.96755296865389</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Upper Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>82.96755296865389</CalcMass>
                    <CalcCG>152.39999999999998</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>304.79999999999995</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Main Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>101.6</Xb>
                            <CalcMass>81.45942013332251</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <Dia>1219.1999999999998</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>6.9139627473878065</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>switch band</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>6.9139627473878065</CalcMass>
                    <CalcCG>12.7</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>25.4</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>37.72818193475864</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-88.89999999999999</Xb>
                            <CalcMass>37.72818193475864</CalcMass>
                            <CalcCG>101.6</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>98.6536</OD>
                            <ID>96.87559999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>238.11480283121188</KnownMass>
                    <Density>688.794</Density>
                    <Material>Cardboard</Material>
                    <Name>Lower Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>238.11480283121188</CalcMass>
                    <CalcCG>431.79999999999995</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>863.5999999999999</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>6</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>25.342205843171634</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>25.342205843171634</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>98.88219999999998</OD>
                            <ID>41.376599999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>37.0</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>engine tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>56.07687916195785</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>285.75</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>41.275</OD>
                            <ID>38.481</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>38.481</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>22.700000000000003</KnownMass>
                                    <Density>2700.0</Density>
                                    <Material>Aluminum</Material>
                                    <Name>motor retainer</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>-0.0</Xb>
                                    <CalcMass>21.198559214035864</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>12.7</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>9</SerialNo>
                                    <OD>50.0126</OD>
                                    <ID>41.401999999999994</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>201.61383282056008</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Freeform fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>17.780000000000005</Xb>
                            <CalcMass>201.61383282056008</CalcMass>
                            <CalcCG>108.14333728746541</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>10</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.953</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>101.6</TabLength>
                            <TabDepth>29.971999999999998</TabDepth>
                            <TabOffset>-19.049999999999997</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>152.39999999999998,0.0|203.2,101.6|203.2,152.39999999999998|127.0,152.39999999999998|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Parachute>
                            <KnownMass>8.850750925286613</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>drogue</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>101.6</Xb>
                            <CalcMass>8.850750925286613</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>300.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>685.8</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.001</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Braided nylon (2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>25.342205843171634</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>254.0</Xb>
                            <CalcMass>25.342205843171634</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>98.88219999999998</OD>
                            <ID>41.376599999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>