<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Aerotech Sumo</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>15</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>599.3605756314824</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>252.0</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>279.4</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>378.4091760083817</CalcMass>
                    <CalcCG>279.4</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>406.4</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>76.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>yonics</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>63.5</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>1</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>354.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>mounting</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>63.5</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>67.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>battery </Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>63.5</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>101.6</BaseDia>
                    <ShoulderLen>101.6</ShoulderLen>
                    <ShoulderOD>98.425</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>910.0</KnownMass>
                    <Density>688.794</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>330.2</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>160.74679255511444</CalcMass>
                    <CalcCG>330.2</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>583.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>32.25487528538354</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>228.6</Xb>
                            <CalcMass>32.25487528538354</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>99.06</OD>
                            <ID>29.8704</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <FinSet>
                            <KnownMass>292.682</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Fin set</Name>
                            <KnownCG>150.952</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>44.45</Xb>
                            <CalcMass>248.77996757081974</CalcMass>
                            <CalcCG>150.952</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>6</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>228.6</RootChord>
                            <TipChord>95.25</TipChord>
                            <SemiSpan>105.41</SemiSpan>
                            <SweepDistance>172.847</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>136.525</TabLength>
                            <TabDepth>35.8648</TabDepth>
                            <TabOffset>50.8</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>12.460258737948767</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>engine tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>215.9</Xb>
                            <CalcMass>12.460258737948767</CalcMass>
                            <CalcCG>152.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>304.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>29.8704</OD>
                            <ID>29.083</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>29.083</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>10.887543175431585</KnownMass>
                                    <Density>1199.78</Density>
                                    <Material>Polycarbonate</Material>
                                    <Name>deflector</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>304.8</Xb>
                                    <CalcMass>10.887543175431585</CalcMass>
                                    <CalcCG>1.5875</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>3.175</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>8</SerialNo>
                                    <OD>60.325</OD>
                                    <ID>0.0</ID>
                                    <UsageCode>4</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <Ring>
                            <KnownMass>32.25487528538354</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>76.2</Xb>
                            <CalcMass>32.25487528538354</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>99.06</OD>
                            <ID>29.8704</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>11.444204329111004</KnownMass>
                            <Density>688.794</Density>
                            <Material>Cardboard</Material>
                            <Name>piston</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>142.24</Xb>
                            <CalcMass>11.444204329111004</CalcMass>
                            <CalcCG>42.8625</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>85.725</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>97.79</OD>
                            <ID>96.52</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>96.52</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>16.16869917764302</KnownMass>
                                    <Density>724.996</Density>
                                    <Material>Aircraft plywood (Birch)</Material>
                                    <Name>piston cap</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>16.16869917764302</CalcMass>
                                    <CalcCG>1.524</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>3.048</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>11</SerialNo>
                                    <OD>96.52</OD>
                                    <ID>0.0</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <MassObject>
                            <KnownMass>42.5243</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>shock cord and buckles</Name>
                            <KnownCG>146.05</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>146.05</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>0.0</KnownMass>
                            <Density>0.0</Density>
                            <Material>1.3 oz. Ripstop Nylon (SkyAngle)</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>95.25</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <Dia>376.453</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1016.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <LaunchLug>
                            <KnownMass>0.6153657910169386</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>469.9</Xb>
                            <CalcMass>0.6153657910169386</CalcMass>
                            <CalcCG>12.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>8.35</OD>
                            <ID>6.35</ID>
                        </LaunchLug>
                        <LaunchLug>
                            <KnownMass>0.6153657910169386</KnownMass>
                            <Density>1049.21</Density>
                            <Material>Polystyrene PS</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>190.5</Xb>
                            <CalcMass>0.6153657910169386</CalcMass>
                            <CalcCG>12.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>8.35</OD>
                            <ID>6.35</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>